/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HospitalsRouteImport } from './routes/hospitals'
import { Route as ApiBackendGenerateRouteImport } from './routes/api/backend/generate'
import { Route as ApiBackendIngestRouteImport } from './routes/api/backend/ingest'
import { Route as ApiBackendTranscribeRouteImport } from './routes/api/backend/transcribe'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalsRoute = HospitalsRouteImport.update({
  id: '/hospitals',
  path: '/hospitals',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBackendGenerateRoute = ApiBackendGenerateRouteImport.update({
  id: '/api/backend/generate',
  path: '/api/backend/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBackendIngestRoute = ApiBackendIngestRouteImport.update({
  id: '/api/backend/ingest',
  path: '/api/backend/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBackendTranscribeRoute = ApiBackendTranscribeRouteImport.update({
  id: '/api/backend/transcribe',
  path: '/api/backend/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hospitals': typeof HospitalsRoute
  '/api/backend/generate': typeof ApiBackendGenerateRoute
  '/api/backend/ingest': typeof ApiBackendIngestRoute
  '/api/backend/transcribe': typeof ApiBackendTranscribeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hospitals': typeof HospitalsRoute
  '/api/backend/generate': typeof ApiBackendGenerateRoute
  '/api/backend/ingest': typeof ApiBackendIngestRoute
  '/api/backend/transcribe': typeof ApiBackendTranscribeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hospitals': typeof HospitalsRoute
  '/api/backend/generate': typeof ApiBackendGenerateRoute
  '/api/backend/ingest': typeof ApiBackendIngestRoute
  '/api/backend/transcribe': typeof ApiBackendTranscribeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/hospitals'
    | '/api/backend/generate'
    | '/api/backend/ingest'
    | '/api/backend/transcribe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/hospitals'
    | '/api/backend/generate'
    | '/api/backend/ingest'
    | '/api/backend/transcribe'
  id:
    | '__root__'
    | '/'
    | '/hospitals'
    | '/api/backend/generate'
    | '/api/backend/ingest'
    | '/api/backend/transcribe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HospitalsRoute: typeof HospitalsRoute
  ApiBackendGenerateRoute: typeof ApiBackendGenerateRoute
  ApiBackendIngestRoute: typeof ApiBackendIngestRoute
  ApiBackendTranscribeRoute: typeof ApiBackendTranscribeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospitals': {
      id: '/hospitals'
      path: '/hospitals'
      fullPath: '/hospitals'
      preLoaderRoute: typeof HospitalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/backend/generate': {
      id: '/api/backend/generate'
      path: '/api/backend/generate'
      fullPath: '/api/backend/generate'
      preLoaderRoute: typeof ApiBackendGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/backend/ingest': {
      id: '/api/backend/ingest'
      path: '/api/backend/ingest'
      fullPath: '/api/backend/ingest'
      preLoaderRoute: typeof ApiBackendIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/backend/transcribe': {
      id: '/api/backend/transcribe'
      path: '/api/backend/transcribe'
      fullPath: '/api/backend/transcribe'
      preLoaderRoute: typeof ApiBackendTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HospitalsRoute: HospitalsRoute,
  ApiBackendGenerateRoute: ApiBackendGenerateRoute,
  ApiBackendIngestRoute: ApiBackendIngestRoute,
  ApiBackendTranscribeRoute: ApiBackendTranscribeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
